// Class automatically generated by Dev-C++ New Class wizard

#ifndef GUYMANAGER_H
#define GUYMANAGER_H

/*
 * No description
 */
class GuyManager
{
	public:
		// class constructor
		GuyManager();
		// class destructor
		~GuyManager();
};

#endif // GUYMANAGER_H
