// Class automatically generated by Dev-C++ New Class wizard

#include "guymanager.h" // class's header file

// class constructor
GuyManager::GuyManager()
{
	// insert your code here
}

// class destructor
GuyManager::~GuyManager()
{
	// insert your code here
}
