# Project: time game
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = time_game_private.res
OBJ  = main.o Guy.o Box.o guymanager.o PropManager.o $(RES)
LINKOBJ  = main.o Guy.o Box.o guymanager.o PropManager.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows ../../lib/liballeg44.dll.a  -g3 
INCS =  -I"C:/Dev-Cpp/include"  -I"F:/User~Docs/Keven/Time Game_SVN/agup1.0/agup-1.0"  -I"C:/Dev-Cpp/include/AGUP" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"F:/User~Docs/Keven/Time Game_SVN/agup1.0/agup-1.0"  -I"C:/Dev-Cpp/include/AGUP" 
BIN  = "time game.exe"
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before "time game.exe" all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "time game.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Guy.o: Guy.cpp
	$(CPP) -c Guy.cpp -o Guy.o $(CXXFLAGS)

Box.o: Box.cpp
	$(CPP) -c Box.cpp -o Box.o $(CXXFLAGS)

guymanager.o: guymanager.cpp
	$(CPP) -c guymanager.cpp -o guymanager.o $(CXXFLAGS)

PropManager.o: PropManager.cpp
	$(CPP) -c PropManager.cpp -o PropManager.o $(CXXFLAGS)

time_game_private.res: time_game_private.rc 
	$(WINDRES) -i time_game_private.rc --input-format=rc -o time_game_private.res -O coff 
