// Class automatically generated by Dev-C++ New Class wizard

#include "Box.h" // class's header file
extern BITMAP* buffer;
extern BITMAP* box_sprite;
// class constructor
Box::Box()
{
	// insert your code here
}

// class destructor
Box::~Box()
{
	// insert your code here
}
void Box::DoDraw()
{
    draw_sprite(buffer, box_sprite, xPos, yPos);
    if(selected)
    {
        rectfill(buffer,xPos,yPos,xPos+GetXSize(),yPos+GetYSize(),makecol(255,0,0));
    }
}
