// Class automatically generated by Dev-C++ New Class wizard

#include "box.h" // class's header file

// class constructor
Box::Box()
{
	// insert your code here
}

// class destructor
Box::~Box()
{
	// insert your code here
}
