// Class automatically generated by Dev-C++ New Class wizard

#include <allegro.h>
//#include "box.h" // class's header file
/*
extern BITMAP* buffer;

extern BITMAP* box_sprite;
// class constructor
Box::Box()
{
   int xPos = 0;
   int yPos = 0;
   double xSpeed = 0;
   double ySpeed = 0;
}

// class destructor
Box::~Box()
{
	// insert your code here
}

void Box::SetData(int newXPos, int newYPos, double newXSpeed, double newYSpeed)
{
     xPos = newXPos;
     yPos = newYPos;
}
void Box::DoDraw()
{
        draw_sprite(buffer, box_sprite, xPos, yPos);
}
void Box::GetData(int& outputXPos, int& outputYPos, double& outputXSpeed, double& outputYSpeed)
{
    outputXPos = xPos;
    outputYPos = yPos;
    outputXSpeed = xSpeed;
    outputYSpeed = ySpeed;
}
*/
