// Class automatically generated by Dev-C++ New Class wizard

#ifndef BOX_H
#define BOX_H

#include "object.h" // inheriting class's header file

/*
 * No description
 */
class Box : public Object
{
	public:
		// class constructor
		Box();
		// class destructor
		~Box();
		void DoDraw();
};

#endif // BOX_H
