// Class automatically generated by Dev-C++ New Class wizard

#ifndef BOX_H
#define BOX_H

/*
 * No description
 */
 /*
class Box : public Object
{

    public:
		// class constructor
		Box();
		// class destructor
		~Box();
		
		void SetData(int newYPos, int newXPos, double newXSpeed, double newYSpeed);
		void DoDraw();
		void GetData(int& outputXPos, int& outputYPos, double& outputXSpeed, double& outputYSpeed);
	private:
        int xPos;
        int yPos;
        double xSpeed;
        double ySpeed;
};
*/
#endif // BOX_H
