// Class automatically generated by Dev-C++ New Class wizard

#ifndef EDITOR_LOG_H
#define EDITOR_LOG_H

/**
 * Takes messages with priorities, and prints them as allegro_messages, or to a file, depending on priority
 */
class Log
{
	public:
		// class constructor
		Log();
		// class destructor
		~Log();
};

#endif // EDITOR_LOG_H
