// Class automatically generated by Dev-C++ New Class wizard

#include "Editor_Log.h" // class's header file

// class constructor
Log::Log()
{
	// insert your code here
}

// class destructor
Log::~Log()
{
	// insert your code here
}
