#ifndef HOURGLASS_ABSOULTE_TIME_DIRECTION_ENUM_H
#define HOURGLASS_ABSOULTE_TIME_DIRECTION_ENUM_H
enum AbsoluteTimeDirectionEnum {
	BACKWARDS = 1,
	PAUSED = 0,
	FORWARDS = -1
};

#endif //HOURGLASS_ABSOULTE_TIME_DIRECTION_ENUM_H

