// Class automatically generated by Dev-C++ New Class wizard

#include "Guy.h" // class's header file
extern BITMAP* buffer;
extern BITMAP* guy_left_stop;
extern BITMAP* guy_right_stop;
// class constructor
Guy::Guy()
{
	// insert your code here
}

// class destructor
Guy::~Guy()
{
	// insert your code here
}
void Guy::DoDraw()
{
    if(drawFacing)
    {
                 draw_sprite(buffer, guy_right_stop, xPos, yPos);
                 if(selected)
                 {
                    rectfill(buffer,xPos,yPos,xPos+GetXSize(),yPos+GetYSize(),makecol(255,0,0));
                 }
             }
             else
             {
                 draw_sprite(buffer, guy_left_stop, xPos, yPos);
                 if(selected)
                 {
                    rectfill(buffer,xPos,yPos,xPos+GetXSize(),yPos+GetYSize(),makecol(255,0,0));
                 }
             }   
}
