// Class automatically generated by Dev-C++ New Class wizard

#ifndef GUY_H
#define GUY_H

#include "object.h" // inheriting class's header file

/*
 * No description
 */
class Guy : public Object
{
	public:
		// class constructor
		Guy();
		// class destructor
		~Guy();
		void DoDraw();
};

#endif // GUY_H
