// Class automatically generated by Dev-C++ New Class wizard

#ifndef GUY_H
#define GUY_H

#include <allegro.h>
#include "object.h"
/*
 * No description
 */
class Guy : public Object
{
	public:
		// class constructor
		Guy();
		// class destructor
		~Guy();
		
		void SetData(int newXPos, int newYPos, double newXSpeed, double newYSpeed, int newType);
		void DoDraw();
		//void GetData(int& outputXPos, int& outputYPos, double& outputXSpeed, double& outputYSpeed);
	private:
        //int xPos;
        //int yPos;
        //double xSpeed;
        //double ySpeed;
        int type;
       // bool drawFacing;
};

#endif // GUY_H
