// Class automatically generated by Dev-C++ New Class wizard

#ifndef HOURGLASS_MENU_H
#define HOURGLASS_MENU_H
#include <allegro.h>
/*
 * No description
 */
class Menu
{
	public:
		// class constructor
		Menu();//int newXPos,int newYPos);
		// class destructor
		~Menu();
		
		//void SetStart(int newXPos,int newYPos);
		int Step();
		void Draw();
		//void Destroy();
	private:
	    int xPos;
	    int yPos;
	    static const int MENU_WIDTH = 125;
	    static const int MENU_HEIGHT = 50;
};

#endif // MENU_H
