// Class automatically generated by Dev-C++ New Class wizard

#include "Menu.h" // class's header file
extern BITMAP* buffer;
extern BITMAP* tempBuffer;
extern BITMAP* menu_box;
extern BITMAP* menu_guy;
extern int pastKeyMouse1;
// class constructor
Menu::Menu()
{
    xPos = mouse_x;
	yPos = mouse_y;
	draw_sprite(tempBuffer, buffer, 0, 0);
}

// class destructor
Menu::~Menu()
{
	draw_sprite(buffer, tempBuffer, 0, 0);
}

//void Menu::SetStart(int newXPos,int newYPos)
//{
 	//xPos = newXPos;
	//yPos = newYPos;
	//draw_sprite(tempBuffer, buffer, 0, 0);
//}

int Menu::Step()
{
    if (mouse_b & 1)
    {
       // allegro_message("y7");
        pastKeyMouse1 = true;
        draw_sprite(buffer, tempBuffer, 0, 0);
        //doingAddObjectMenu = false;
        //Destroy();
        if (mouse_x > xPos && 
            mouse_x < (xPos + MENU_WIDTH) && 
            mouse_y > yPos && 
            mouse_y < (yPos + MENU_HEIGHT))
        {
            return(0); //add guy
        }
        else if (mouse_x > xPos &&
                mouse_x < (xPos + MENU_WIDTH) &&
                mouse_y > (yPos + MENU_HEIGHT) &&
                mouse_y < (yPos + MENU_HEIGHT*2))
        {
            return(1); //add box
        }
        else
        {
            return(-1); //continue, doing nothing.
        }
    }
    else
    {
        return(-1); //continue, doing nothing.
    }
    //Draw();
}

void Menu::Draw()
{
    //allegro_message("y8");
    int noOfMenuItems = 0;
    draw_sprite(buffer, menu_guy, xPos, yPos + noOfMenuItems*MENU_HEIGHT);
    noOfMenuItems++;
    draw_sprite(buffer, menu_box, xPos, yPos + noOfMenuItems*MENU_HEIGHT);
    noOfMenuItems++;
}

//void Menu::Destroy()
//{
 //   draw_sprite(buffer, tempBuffer, 0, 0);
//}
