// Class automatically generated by Dev-C++ New Class wizard

#ifndef OBJECT_H
#define OBJECT_H

 // inheriting class's header file

/*
 * No description
 */
const int GUY_WIDTH = 24;
const int GUY_HEIGHT = 32;

const int BOX_WIDTH = 32;
const int BOX_HEIGHT = 32;
class Object
{
	public:
		// class constructor
		Object();
		// class destructor
		~Object();
		
	    void SetData(int newXPos, int newYPos, double newXSpeed, double newYSpeed, int newType);
		void SetPos(int newXPos, int newYPos);
        void DoDraw();
		void GetData(int& outputXPos, int& outputYPos, double& outputXSpeed, double& outputYSpeed);
	    int GetType();
	    void SetSelected(bool newSelected);
	    bool DoSelectionCheck();
    protected:
        int xPos;
        int yPos;
        double xSpeed;
        double ySpeed;
        bool drawFacing;
        int type;
        bool selected;
        int GetXSize();
        int GetYSize();
};

#endif // OBJECT_H
