// Class automatically generated by Dev-C++ New Class wizard

#include "SwitchingInput.h" // class's header file
extern BITMAP* buffer;

// class constructor
SwitchingInput::SwitchingInput() :
    currentValue(false),
    isToggledOn(false)
{

}

// class destructor
SwitchingInput::~SwitchingInput()
{
	// insert your code here
}

void SwitchingInput::Add(const int keyCode, const RepeatType repeatType, int shiftCode)
{
     assignedCombinations.push_back(new KeyCombination(keyCode,repeatType,shiftCode));
}

void SwitchingInput::Add(const int keyCode, const RepeatType repeatType)
{
     assignedCombinations.push_back(new KeyCombination(keyCode,repeatType));
}

void SwitchingInput::Update()
{
     const bool pastValue = currentValue;
     currentValue = false;
     for(std::list<KeyCombination*>::iterator it = assignedCombinations.begin(); it != assignedCombinations.end(); ++it)
     {
         (*it)->UpdatePressed();
         switch((*it)->GetType())
         {
             case PRESS:
                 //textout_ex(buffer, font, "a", 10, 10, makecol(0, 0, 255), -1);
                 if((*it)->GetPressed())
                 {
                     //textout_ex(buffer, font, "b", 10, 30, makecol(0, 0, 255), -1);
                     if(!(*it)->GetPastPressed())
                     {
                     //    textout_ex(buffer, font, "c", 10, 50, makecol(0, 0, 255), -1);
                         currentValue = true;
                     }
                    // currentPress = true;
                 }
                 break;
             case RELEASE:
              //   textout_ex(buffer, font, "e", 1014, 10, makecol(0, 0, 255), -1);
                 
                 if(!((*it)->GetPressed()))
                 {
            //         textout_ex(buffer, font, "g", 1014, 50, makecol(0, 0, 255), -1);
                     if((*it)->GetPastPressed())
                     {
               //          textout_ex(buffer, font, "i", 1014, 70, makecol(0, 0, 255), -1);
                         currentValue = true;
                     }
                 }
                 break;
             case TOGGLE_ON_PRESS:
                 //textout_ex(buffer, font, "a", 10, 10, makecol(0, 0, 255), -1);
                 if((*it)->GetPressed())
                 {
                     //textout_ex(buffer, font, "b", 10, 30, makecol(0, 0, 255), -1);
                     if(!(*it)->GetPastPressed())
                     {
                         //textout_ex(buffer, font, "c", 10, 50, makecol(0, 0, 255), -1);
                         if(isToggledOn)
                         {
                             isToggledOn = false;
                         }
                         else
                         {
                             isToggledOn = true;
                         }
                     }
                   //  currentPress = true;
                 }
                 if (isToggledOn)
                 {
                     currentValue = true;
                 }
                 break;
             case TOGGLE_ON_RELEASE:
                 if(!((*it)->GetPressed()))
                 {
            //         textout_ex(buffer, font, "g", 1014, 50, makecol(0, 0, 255), -1);
                     if((*it)->GetPastPressed())
                     {
               //          textout_ex(buffer, font, "i", 1014, 70, makecol(0, 0, 255), -1);
                         if(isToggledOn)
                         {
                             isToggledOn = false;
                         }
                         else
                         {
                             isToggledOn = true;
                         }
                     }
                 }
                 if (isToggledOn)
                 {
                     currentValue = true;            
                 }
                 break;
            case HOLD:
                 if((*it)->GetPressed())
                 {
                     currentValue = true;
                 }
                 break;
            default:
            allegro_message("switch((*it)->GetType()) in SwitchingInput::Update() fell through to default\n"
                             "this should never happen!");
         }
     }
}

bool SwitchingInput::GetCurrentValue()
{
    return(currentValue);
}

void SwitchingInput::Reset()
{
    while (assignedCombinations.size() != 0)
    {
       delete assignedCombinations.back();
       assignedCombinations.pop_back();
    }
    currentValue = false;
    isToggledOn = false;
}
